*** Settings ***
Documentation    This suite directory is used as demo data to integrate the robot framework test documentation generated by testdoc into an already existing, static mkdocs page!
...
...    Testdoc is capable of building your complete mkdocs configuration in case you want to combine it with the test documentation generation!