name: Build Python Package

on:
  push:
    paths:
      - '**.py'
      - '**.html'
      - pyproject.toml
  pull_request:
    paths:
      - '**.py'
      - '**.html'
      - pyproject.toml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Build Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build ruff pytest

    - name: Lint with ruff
      run: ruff check .

    - name: Build package
      run: python -m build

    - name: Test CLI command
      run: |
        pip install .
        testdoc --help

    - name: Run unit tests
      run: pytest atest/

    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        pip install twine
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*
