name: GitHub Release Creation

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*a*'
      - '!v*.*.*b*'
      - '!v*.*.*rc*'

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}